### ISSUE TITLE
Bug : Flame Core causing crashes in the Awakened One fight

### ISSUE THREAD

**Issue by PABessero** [Moocowsgomoo/StS-ConstructMod#10]
# How it happened :
I was fighting the Awakened One on the end of the 3rd zone, and had just killed its first form so it was in its transformation state. At that point I had just redrawn one of my Flame Core (might have been Laser Core but i think it was Flame Core) and decided to play it (still dont know why) which caused my game to CTD.

# Exception :
```java
20:11:09.008 ERROR core.CardCrawlGame> Exception caught
java.lang.NullPointerException: null
	at com.megacrit.cardcrawl.actions.common.DamageAction.update(DamageAction.java:64) ~[desktop-1.0.jar:?]
	at com.megacrit.cardcrawl.actions.GameActionManager.update(GameActionManager.java:152) ~[?:?]
	at com.megacrit.cardcrawl.rooms.AbstractRoom.update(AbstractRoom.java:255) ~[?:?]
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.update(AbstractDungeon.java:2631) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:780) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:376) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126) [desktop-1.0.jar:?]
20:11:09.024 INFO core.CardCrawlGame> PAUSE()
20:11:09.024 INFO core.CardCrawlGame> Game shutting down...
20:11:09.025 INFO helpers.FileSaver> Save thread interrupted!
20:11:09.025 INFO helpers.FileSaver> Save thread will die now.
```
# Comment(s) :
Here is the full log
[SlayTheSpire_201807022011_1.log](https://github.com/Moocowsgomoo/StS-ConstructMod/files/2156683/SlayTheSpire_201807022011_1.log)

**Comment by Moocowsgomoo** [comment]
Fixed in the latest release 0.6.8. Thanks for the report!
