### ISSUE TITLE
Not sure if this is construct related or not, ut take a look, sending it here because your mod is mentioned in the error.

### ISSUE THREAD

**Issue by Lunaraia** [Moocowsgomoo/StS-ConstructMod#19]
Exception: java.util.ConcurrentModificationException
16:52:58.148 ERROR core.CardCrawlGame> Exception caught
java.util.ConcurrentModificationException: null
	at java.util.ArrayList$Itr.checkForComodification(Unknown Source) ~[?:1.8.0_171]
	at java.util.ArrayList$Itr.next(Unknown Source) ~[?:1.8.0_171]
	at basemod.BaseMod.publishPostDungeonInitialize(BaseMod.java:1887) ~[?:?]
	at basemod.patches.com.megacrit.cardcrawl.dungeons.AbstractDungeon.PostDungeonInitializeHook.Postfix(PostDungeonInitializeHook.java:9) ~[BaseMod.jar:?]
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.initializeRelicList(AbstractDungeon.java:1766) ~[?:?]
	at com.megacrit.cardcrawl.dungeons.Exordium.<init>(Exordium.java:52) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.getDungeon(CardCrawlGame.java:1291) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:810) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:415) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126) [desktop-1.0.jar:?]
Controllers: removed manager for application, 0 managers active
16:52:59.157 INFO core.CardCrawlGame> PAUSE()
16:52:59.157 INFO core.CardCrawlGame> Game shutting down...
16:53:01.573 INFO helpers.File> Failed to copy file=D:\SteamLibrary\steamapps\common\SlayTheSpire\preferences\THE_CONSTRUCT_MOD
java.nio.channels.ClosedByInterruptException: null
	at java.nio.channels.spi.AbstractInterruptibleChannel.end(Unknown Source) ~[?:1.8.0_171]
	at sun.nio.ch.FileChannelImpl.size(Unknown Source) ~[?:1.8.0_171]
	at java.nio.file.Files.readAllBytes(Unknown Source) ~[?:1.8.0_171]
	at com.megacrit.cardcrawl.helpers.File.validateWrite(File.java:140) ~[desktop-1.0.jar:?]
	at com.megacrit.cardcrawl.helpers.File.copyAndValidate(File.java:97) [desktop-1.0.jar:?]
	at com.megacrit.cardcrawl.helpers.File.save(File.java:49) [desktop-1.0.jar:?]
	at com.megacrit.cardcrawl.helpers.FileSaver.consume(FileSaver.java:42) [desktop-1.0.jar:?]
	at com.megacrit.cardcrawl.helpers.FileSaver.run(FileSaver.java:25) [desktop-1.0.jar:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]
16:53:01.574 INFO helpers.File> java.lang.InterruptedException: sleep interrupted

**Comment by Moocowsgomoo** [comment]
Hmm, could you provide a bit more context on when the error occurred / what you were doing?
Some specific questions:
 - What other mods did you have active?
 - Does this keep happening, or did it work next time you tried to load the game?
 - If you go to that file path (D:\SteamLibrary\steamapps\common\SlayTheSpire\preferences), is there a THE_CONSTRUCT_MOD file there at all?

**Comment by Lunaraia** [comment]
The mods that were active at the time were: Basemod, BetterRewards, Black Mage, Colored Map, Construct Mod (obviously), FechMod, FruityMod, HexCores, MadScienceMod, MoreRelics, NecroMod, ReplayTheSpire, STS_Alwayswhale, SynergyRelic and WitchMod.

As for what I were doing. well the latest release put Endless into the main branch so I were on an Endless Run, had just beaten Act 3 and were gong back to see Neow when it just CTD'd me with that error.

There was a THE_CONSTRUCT_MOD file in the preferences menu so not sure why it didn't find it.

Upon starting up the game and retrying it just now (haven't played since this bug occurred) I could enter the new cycle just fine and going for another 3 cycles it still have not crashed, so I am honestly not sure whats going on.

**Comment by Moocowsgomoo** [comment]
Yeah, that's pretty weird - I just tested an endless run with that setup and it didn't crash or anything. I'll leave the issue up in case you or anyone else experiences it again. It's probably an interaction between two or more mods, but with your list that's a lot of options :)

**Comment by Lunaraia** [comment]
I will put up a copy of this on Basemod's issue tracker part as that is also mentioned, might be that they can make heads or tails of this.

mentioned part is: basemod.patches.com.megacrit.cardcrawl.dungeons.AbstractDungeon.PostDungeonInitializeHook.Postfix(PostDungeonInitializeHook.java:9) ~[BaseMod.jar:?]

so this might actually be a Basemod issue
