### ISSUE TITLE
Hyperbeam crash

### ISSUE THREAD

**Issue by AisuRyuuko** [Moocowsgomoo/StS-ConstructMod#2]
Playing Hyperbeam causes the game to crash. (Week 30 patch)

Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: java.lang.NoSuchMethodError: com.megacrit.cardcrawl.actions.common.MakeTempCardInDrawPileAction.<init>(Lcom/megacrit/cardcrawl/core/AbstractCreature;Lcom/megacrit/cardcrawl/core/AbstractCreature;Lcom/megacrit/cardcrawl/cards/AbstractCard;IZZ)V
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:133)
Caused by: java.lang.NoSuchMethodError: com.megacrit.cardcrawl.actions.common.MakeTempCardInDrawPileAction.<init>(Lcom/megacrit/cardcrawl/core/AbstractCreature;Lcom/megacrit/cardcrawl/core/AbstractCreature;Lcom/megacrit/cardcrawl/cards/AbstractCard;IZZ)V
	at constructmod.cards.HyperBeam.use(HyperBeam.java:53)
	at com.megacrit.cardcrawl.characters.AbstractPlayer.useCard(AbstractPlayer.java:1426)
	at com.megacrit.cardcrawl.actions.GameActionManager.getNextAction(GameActionManager.java:284)
	at com.megacrit.cardcrawl.actions.GameActionManager.update(GameActionManager.java:148)
	at com.megacrit.cardcrawl.rooms.AbstractRoom.update(AbstractRoom.java:255)
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.update(AbstractDungeon.java:2615)
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:825)
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:376)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)

**Comment by KongMD-Steam** [comment]
The StS devs changed the arguments for the MakeTempCardInDrawPileAction() function. Here's how to implement the fix: https://github.com/gskleres/FruityMod-StS/commit/68d95fbb5ebdfebd295b7fda221470af54027dd7

**Comment by Moocowsgomoo** [comment]
Fixed with the latest release.
