### ISSUE TITLE
Wedding Ring crash?

### ISSUE THREAD

**Issue by SirHaesslich** [Moocowsgomoo/StS-ConstructMod#22]
I am not sure the fault is in the Construct code, but the crash happened after the relic trigger(apparently). Game died when I played the Charge Battery, which triggered the Wedding Ring, playing for free the [AOE + channel Dark Orb] card that also was in my hand(maybe that was the reason). The only mod specifically mentioned is the RPTS one, which is confusing. Submitting it to both mods to be sure, am aware of possible incompatibility, but one can hope.
Exception: java.lang.NullPointerException
19:45:30.814 ERROR core.CardCrawlGame> Exception caught
java.lang.NullPointerException: null
	at replayTheSpire.patches.PlayerDamagePatch.Postfix(PlayerDamagePatch.java:49) ~[ReplayTheSpireMod.jar:?]
	at com.megacrit.cardcrawl.characters.AbstractPlayer.damage(AbstractPlayer.java:1617) ~[?:?]
	at com.megacrit.cardcrawl.actions.common.DamageAction.update(DamageAction.java:83) ~[desktop-1.0.jar:?]
	at com.megacrit.cardcrawl.actions.GameActionManager.update(GameActionManager.java:152) ~[?:?]
	at com.megacrit.cardcrawl.rooms.AbstractRoom.update(AbstractRoom.java:258) ~[?:?]
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.update(AbstractDungeon.java:2653) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:893) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:466) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126) [desktop-1.0.jar:?]

**Comment by Moocowsgomoo** [comment]
Some Wedding Ring issues were fixed in the [latest version](https://github.com/Moocowsgomoo/StS-ConstructMod/releases), and I think this *might* have been fixed in Replay as well? Closing for now, feel free to reopen it if it still occurs.
