### ISSUE TITLE
Incorrect Save Behavior

### ISSUE THREAD

**Issue by JBrandon369** [Moocowsgomoo/StS-ConstructMod#25]
For some reason every time i restart slay the spire the game somehow loads a mad scientist save i abandon a long time ago. if i abandon the run again i can then continue my existing run or start a new run if i didn't quit my last session with a run in progress. i imagine this is some kind of interaction between my mods and maybe a corrupted save. the only exception in the log is below, and it appears 3-4 times. please let me know what additional information i can provide to help diagnose this problem or if i need to notify other mod authors.

[ModTheSpireLog.txt](https://github.com/Moocowsgomoo/StS-ConstructMod/files/2485380/ModTheSpireLog.txt)

00:17:00.397 INFO constructmod.ConstructMod> ConstructMod | Loading Ring Data...

java.lang.NumberFormatException: null
	at java.lang.Integer.parseInt(Integer.java:542)
	at java.lang.Integer.parseInt(Integer.java:615)
	at com.evacipated.cardcrawl.modthespire.lib.SpireConfig.getInt(SpireConfig.java:84)
	at constructmod.ConstructMod.loadRingData(ConstructMod.java:181)
	at constructmod.patches.SavePatch$LoadGameByString.Prefix(SavePatch.java:23)
	at com.megacrit.cardcrawl.saveAndContinue.SaveAndContinue.loadSaveFile(SaveAndContinue.java)
	at com.megacrit.cardcrawl.saveAndContinue.SaveAndContinue.saveExistsAndNotCorrupted(SaveAndContinue.java:49)
	at basemod.abstracts.CustomPlayer.saveFileExists(CustomPlayer.java:213)
	at com.megacrit.cardcrawl.characters.CharacterManager.anySaveFileExists(CharacterManager.java:49)
	at com.megacrit.cardcrawl.screens.mainMenu.MainMenuScreen.setMainMenuButtons(MainMenuScreen.java:148)
	at com.megacrit.cardcrawl.screens.mainMenu.MainMenuScreen.<init>(MainMenuScreen.java:129)
	at com.megacrit.cardcrawl.screens.mainMenu.MainMenuScreen.<init>(MainMenuScreen.java:105)
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:797)
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:460)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)00:17:00.458

**Comment by Moocowsgomoo** [comment]
As you suspected, this might be a corrupted save that wasn't deleted properly. The first thing to try is just deleting the old autosave file. From your main Slay the Spire directory, look in the "saves" folder and delete MAD_SCIENTIST.autosave and MAD_SCIENTIST.autosave.backUp from that folder. (No permanent data is stored here, only in-progress runs; you can even try deleting everything inside the saves folder if you don't have any runs you want to continue).

**Comment by JBrandon369** [comment]
Pretty sure this is being caused by steam cloud. i don't know what the trigger is but for some reason it keeps restoring my cloud save which some how got some of my mod saves into
