### ISSUE TITLE
found 2 cards that crash the game everytime i use them

### ISSUE THREAD

**Issue by DADADANK** [Moocowsgomoo/StS-ConstructMod#3]
the cards backup and accumulate crash the game anytime they are trying to copy a card. to make sure it wasn't the card i was trying to copy i used the defend card and it still crashed.

02:59:38.127 DEBUG basemod.BaseMod> Copying card Defend with 0 upgrades.
02:59:38.128 INFO unlock.UnlockTracker> Already seen: Defend_Gold
02:59:38.129 DEBUG basemod.BaseMod> Copying card Defend with 0 upgrades.

Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: java.lang.NoSuchMethodError: com.megacrit.cardcrawl.actions.common.MakeTempCardInDrawPileAction.<init>(Lcom/megacrit/cardcrawl/core/AbstractCreature;Lcom/megacrit/cardcrawl/core/AbstractCreature;Lcom/megacrit/cardcrawl/cards/AbstractCard;IZZ)V
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:133)
Caused by: java.lang.NoSuchMethodError: com.megacrit.cardcrawl.actions.common.MakeTempCardInDrawPileAction.<init>(Lcom/megacrit/cardcrawl/core/AbstractCreature;Lcom/megacrit/cardcrawl/core/AbstractCreature;Lcom/megacrit/cardcrawl/cards/AbstractCard;IZZ)V
	at constructmod.actions.BackupAction.update(BackupAction.java:71)
	at com.megacrit.cardcrawl.actions.GameActionManager.update(GameActionManager.java:152)
	at com.megacrit.cardcrawl.rooms.AbstractRoom.update(AbstractRoom.java:255)
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.update(AbstractDungeon.java:2675)
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:825)
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:376)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)

**Comment by KongMD-Steam** [comment]
The devs changed the arguments for the MakeTempCardInDrawPileAction() function. Here's how to implement the fix: https://github.com/gskleres/FruityMod-StS/commit/68d95fbb5ebdfebd295b7fda221470af54027dd7

**Comment by Moocowsgomoo** [comment]
Fixed with the latest release. Thanks KongMD for the link on how to fix it!
