### ISSUE TITLE
Crash with Slimebound relic

### ISSUE THREAD

**Issue by tehscott** [Moocowsgomoo/StS-ConstructMod#30]
I got a relic (from a mod I don't remember) that replaced all my relics with random ones. One of those random ones was the `Slimebound` starting relic. Now, at the start of my turn, it crashes with:

```
04:42:03.656 INFO slimebound.SlimeboundMod> Slime spawn projectile firing
04:42:04.281 INFO slimebound.SlimeboundMod> Channeling slime orb
Exception: java.lang.ClassCastException: constructmod.characters.TheConstruct cannot be cast to slimebound.characters.SlimeboundCharacter
04:42:04.817 ERROR core.CardCrawlGame> Exception caught
java.lang.ClassCastException: constructmod.characters.TheConstruct cannot be cast to slimebound.characters.SlimeboundCharacter
	at slimebound.orbs.SpawnedSlime.setSlot(SpawnedSlime.java:168) ~[SlimeboundMod.jar:?]
	at com.megacrit.cardcrawl.characters.AbstractPlayer.channelOrb(AbstractPlayer.java:2759) ~[?:?]
	at com.megacrit.cardcrawl.actions.defect.ChannelAction.update(ChannelAction.java:27) ~[desktop-1.0.jar:?]
	at com.megacrit.cardcrawl.actions.GameActionManager.update(GameActionManager.java:155) ~[?:?]
	at com.megacrit.cardcrawl.rooms.AbstractRoom.update(AbstractRoom.java:283) ~[?:?]
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.update(AbstractDungeon.java:2531) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:883) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:435) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126) [desktop-1.0.jar:?]
```

**Comment by Moocowsgomoo** [comment]
Looks like this was fixed on Slimebound's side - getting their starter relic should work fine now!
