### ISSUE TITLE
Out of Bounds exception when playing Panic Fire

### ISSUE THREAD

**Issue by Lunaraia** [Moocowsgomoo/StS-ConstructMod#9]
Exception: java.lang.IndexOutOfBoundsException: Index: 30, Size: 30
12:38:32.418 ERROR core.CardCrawlGame> Exception caught
java.lang.IndexOutOfBoundsException: Index: 30, Size: 30
	at java.util.ArrayList.rangeCheck(Unknown Source) ~[?:1.8.0_171]
	at java.util.ArrayList.get(Unknown Source) ~[?:1.8.0_171]
	at constructmod.cards.PanicFire.use(PanicFire.java:49) ~[ConstructMod.jar:?]
	at com.megacrit.cardcrawl.characters.AbstractPlayer.useCard(AbstractPlayer.java:1426) ~[?:?]
	at com.megacrit.cardcrawl.actions.GameActionManager.getNextAction(GameActionManager.java:284) ~[?:?]
	at com.megacrit.cardcrawl.actions.GameActionManager.update(GameActionManager.java:148) ~[?:?]
	at com.megacrit.cardcrawl.rooms.AbstractRoom.update(AbstractRoom.java:255) ~[?:?]
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.update(AbstractDungeon.java:2631) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:780) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:376) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126) [desktop-1.0.jar:?]
Controllers: removed manager for application, 0 managers active
12:38:32.434 INFO core.CardCrawlGame> PAUSE()
12:38:32.434 INFO core.CardCrawlGame> Game shutting down...
12:38:32.435 INFO helpers.FileSaver> Save thread interrupted!
12:38:32.435 INFO helpers.FileSaver> Save thread will die now.
Game closed.

**Comment by Moocowsgomoo** [comment]
Fixed with the latest release (0.6.6). Thanks for the report!
